---
- name: python dependencies
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - build-essential
    - checkinstall
    - libreadline-gplv2-dev
    - libncursesw5-dev
    - libssl-dev
    - libsqlite3-dev
    - tk-dev
    - libgdbm-dev
    - libc6-dev
    - libbz2-dev
    - zlib1g-dev
    - openssl
    - libffi-dev
    - python3-dev
    - python3-setuptools

- name: set directory of downloaded python
  set_fact:
    python_dir: /tmp/Python-3.7.0

- name: python download directory
  file:
    path: "{{ python_dir }}"
    owner: ubuntu
    group: ubuntu
    mode: 0755
    state: directory

- name: Download and unarchive python 3.7
  unarchive:
    src: https://www.python.org/ftp/python/3.7.0/Python-3.7.0.tar.xz
    dest: /tmp
    remote_src: yes

- name: configure
  command: ./configure
  args:
    chdir: "{{ python_dir }}"

- name: make install
  command: make altinstall
  args:
    chdir: "{{ python_dir }}"
